project:
  type: website
  render:
    - index.qmd
    - 404.qmd
    - blogs/cs_328_writing_assignment/writing_assignment.ipynb

website:
  title: "Yuvraj Rathod"
  
  navbar:
    pinned: true
    left:
      - text: About
        href: /
      - text: Blog
        href: /blogs/cs_328_writing_assignment/

format:
  html:
    smooth-scroll: true
    theme:
      light: theme-light.scss
      dark: theme-dark.scss
    css: styles.css
    highlight-style: github
